### PR TITLE
Fix a crash with the new version of KubeJS 6

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
Yet another event handler rework by Lat; these kinds of breaking changes should however, become a more rare occurrence as we near the actual *release* of KubeJS 6 ^^

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
*Damnit GitHub, please target the right branch on the first go for once...*

**Comment by desht** [comment]
Is this change backwards compatible with the existing version of KubeJS?  If not, we also need to change the min dependency version of KubeJS in `mods.toml` and `fabric.mod.json`.

**Review by desht — COMMENTED** [review]
Is this change backwards compatible with the existing version of KubeJS? If not, we also need to change the min dependency version of KubeJS in mods.toml and fabric.mod.json.

**Comment by MaxNeedsSnacks** [comment]
It's not and we'll need to bump the version, yeah

**Pull request merged**
